package jp.co.axa.apidemo.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import jp.co.axa.apidemo.dto.EmployeeDto;
import lombok.Getter;
import lombok.Setter;

/**
 * Entity definition for an employee.
 */
@Entity
@Table(name = "EMPLOYEE")
public class Employee {

    /**
     * Id of the employee. Automatically generated by the database.
     */
    @Getter
    @Setter
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the employee.
     */
    @Getter
    @Setter
    @Column(name = "EMPLOYEE_NAME")
    private String name;

    /**
     * Salary of the employee.
     */
    @Getter
    @Setter
    @Column(name = "EMPLOYEE_SALARY")
    private Integer salary;

    /**
     * Department the employee is affiliated with.
     */
    @Getter
    @Setter
    @Column(name = "DEPARTMENT")
    private String department;

    public static Employee fromDto(EmployeeDto employeeDto) {
        Employee emp = new Employee();
        emp.name = employeeDto.getName();
        emp.department = employeeDto.getDepartment();
        emp.salary = employeeDto.getSalary();
      
        return emp;
    }

    public void merge(Employee other) {
        if (other.getName() != null) name = other.getName();
        if (other.getDepartment() != null) department = other.getDepartment();
        if (other.getSalary() != null) salary = other.getSalary();
    }
}
